---

- hosts: nodes
  become: true

  tasks:
   - name: Install aptitude using apt
     apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

   - name: Install list of packages
     apt:
       name: ['apt-transport-https','ca-certificates','curl','software-properties-common']
       state: present
       update_cache: yes

   - name: Add Docker GPG apt Key
     apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
 
   - name: Add Docker Repository
     apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
        state: present
        update_cache: yes
        
   - name: Acceing the version for docker     
     shell: apt-cache madison docker-ce | grep 18.06 | head -1 | awk '{print $3}'
     register: command_result

   - debug: msg={{ command_result.stdout }}

   - name: Update apt and install docker-ce
     apt: update_cache=yes name=docker-ce={{ command_result.stdout }}
