---
- hosts: nodes
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

      #    - name: Install required system packages
      # apt: 
      # name: [‘iptables’, ‘arptables’, ‘ebtables’,’apt-transport-https’,’curl’]
      # state: latest 
      # update_cache: yes

    - name: add Kubernetes apt-key
      apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
    
    - name: add Kubernetes' APT repository
      apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
       filename: 'kubernetes'
       update_cache: yes

    - name: install kubelet
      apt:
       name: kubelet=1.14.0-00
       state: present
    
    - name: install kubeadm
      apt:
       name: kubeadm=1.14.0-00
       state: present

    - name: install kubectl
      apt:
       name: kubectl=1.14.0-00
       state: present
       force: yes
