[masters]
master-1 ansible_host=192.168.5.11 ansible_user=root
Master-2 ansible_host=192.168.5.12 ansible_user=root
Master-3 ansible_host=192.168.5.13 ansible_user=root

[workers]
worker1 ansible_host=192.168.5.21 ansible_user=root
worker2 ansible_host=192.168.5.22 ansible_user=root

[nodes:children]
masters
workers

[loadbalancer]
lb ansible_host=192.168.5.30 ansible_user=root
