---

- name: Configure cluster
  hosts: master-1

  tasks:
    - name: Execute kubeadm Command
      shell: kubeadm init --config=/root/kube-config.yaml

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

- name: running on master 2 
  hosts: master-2
  tasks:
    - name: Transfer file from master-1 to master-2
      synchronize:
        src: /etc/kubernetes/pki
        dest: /etc/kubernetes/pki
        mode: push
        recursive: yes
      delegate_to: master-1
      
    - name: Search files to be deleted
      find:
        paths: /etc/kubernetes/pki
        patterns: "apiserver.*"
        use_regex: true
      register: wildcard_files_to_delete

    - name: Remove files after finding
      file:
         path: "{{ item.path }}"
         state: absent
      with_items: "{{ wildcard_files_to_delete.files }}"  

    - name: Execute kubeadm Command
      shell: kubeadm init --config=/root/kube-config.yaml


- name: master-3
  hosts: master-3
  tasks:
    - name: Transfer file from master-1 to master-3
      synchronize:
        src: /etc/kubernetes/pki
        dest: /etc/kubernetes/pki
        mode: push
        recursive: yes
      delegate_to: master-1

    - name: Search files to be deleted
      find:
        paths: /etc/kubernetes/pki
        patterns: "apiserver.*"
        use_regex: true
      register: wildcard_files_to_delete

    - name: Remove files after finding
      file:
         path: "{{ item.path }}"
         state: absent
      with_items: "{{ wildcard_files_to_delete.files }}" 

    - name: Execute kubeadm Command
      shell: kubeadm init --config=/root/kube-config.yaml  
